### ISSUE TITLE
Publish a release to Bintray

### ISSUE THREAD

**Issue by 2m** [yoshiyoshifujii/sbt-aws-serverless#2]
It is not possible to use this plugin with [coursier](https://github.com/alexarchambault/coursier) package fetcher. Consider publishing sbt plugins to [Bintray](http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html) so it can be resolved as a regular build dependency.

**Comment by yoshiyoshifujii** [comment]
I published to Sonatype.

``` sbt
addSbtPlugin("com.github.yoshiyoshifujii" % "sbt-aws-serverless" % "1.5.0")
```

**Comment by 2m** [comment]
Thank you!
